### ISSUE TITLE
 development

### ISSUE THREAD

**Issue by wilfried18** [BrandoCommando/OpenExplorer#2]
The application is still in development? last updated in 2012 days

**Comment by mase76** [comment]
Same question here. This is the best open source filemanager on Android.
It would be sad, if there is no further development.

**Comment by BrandoCommando** [comment]
Actually, I've recently restarted development. Currently I'm working on a separate, but related, web-based project for aggregating Cloud service accounts. Eventually I will probably make use of that service for Open Explorer.

**Comment by wilfried18** [comment]
his may be a good idea, even if having dropbox, drive, etc. can be a inconviniant for opensource implementation
